### ISSUE TITLE
Angular 2 + Redux Docs is Broken

### ISSUE THREAD

**Issue by jancarloviray** [apollostack/angular2-docs#29]
I was searching online for "angular apollo redux" and I saw your doc page:

[http://dev.apollodata.com/angular2/redux.html](http://dev.apollodata.com/angular2/redux.html)

- the logo overflows
- docs seems to be about React

![screenshot 2017-01-19 05 29 54](https://cloud.githubusercontent.com/assets/1477140/22108598/c8e50078-de08-11e6-8123-e9af413d6fa1.png)

**Comment by Urigo** [comment]
thank for reporting, fixed [here](https://github.com/apollostack/angular2-docs/pull/30)
