### ISSUE TITLE
overlapping displays

### ISSUE THREAD

**Issue by Hongbo-Miao** [apollostack/angular2-docs#3]
Please fix the UI. It overlapping displays now:

http://dev.apollodata.com/angular2/redux.html
http://dev.apollodata.com/angular2/server-side-rendering.html

![image](https://cloud.githubusercontent.com/assets/3375461/18937042/92b51048-85ba-11e6-8ea3-b1ad7f4b613a.png)

**Comment by kamilkisiela** [comment]
Where did you get the links to Redux and SSR? :) It's not in the menu! So there are at least two places when it needs to be updated.

btw: I'll create SSR chapter since Universal supports now Angular 2.0
